# .github/workflows/coverage.yml
name: Post coverage comment

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  comment:
    name: Add coverage comment
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: read
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      # Doesn't use actions/checkout@v3 for security reasons
      - name: Post comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          COMMENT_ARTIFACT_NAME: python-coverage-comment-action
          COMMENT_FILENAME: python-coverage-comment-action.txt