on: [push]

jobs:
  build:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: |
          sudo apt-get update -qq
          sudo apt-get install -qq stockfish